version: '3.2'
services:
  jenkins:
    image: jenkinsci/blueocean:latest
    restart: always
    volumes:
      - /data/jenkins:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - JENKINS_HOST_HOME = /data/jenkins
    ports:
      - "8080:8080"
      - "5000:5000"
      - "50000:50000"
    networks:
      - jenkins
networks:
   jenkins:
      driver: bridge
